trailing_comma = "Vertical"
imports_granularity = "Crate"
edition = "2021"
imports_layout = "HorizontalVertical"
overflow_delimited_expr = false
group_imports = "StdExternalCrate"
reorder_impl_items = true
struct_lit_single_line = true
use_small_heuristics = "Max"